version: '3'
services:
  server:
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: mongo
    restart: always
    ports: 
    - 27017:27017
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=abolfazl
      - MONGO_INITDB_ROOT_PASSWORD=lvrp1383

volumes:
  mongo-db: